# Generated by Django 4.1.4 on 2023-02-11 12:25

from django.db import migrations, models
import django.db.models.deletion
import list.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="To_DO_List",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="List",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("due_date", models.DateField(default=list.models.dueDate)),
                (
                    "To_DoList",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="list.to_do_list",
                    ),
                ),
            ],
        ),
    ]
